# Generated by Django 5.0.1 on 2024-02-29 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_category_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Category_Name',
            new_name='category_name',
        ),
    ]
